name: Run Unit Tests

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup conda
      uses: s-weigand/setup-conda@v1
      with:
        activate-conda: true
    - name: Install numpy, cython, ipywidgets, natsort, pandas, matplotlib, tqdm, seaborn with conda
      run: conda install numpy=1.20.1 cython=0.29.23 ipywidgets=7.6.3 natsort=7.1.1 pandas=1.2.4 matplotlib=3.3.4 tqdm=4.31.1 seaborn=0.11.1
    - name: compile cython extension for simulator
      run: python setup.py build_ext --inplace
    - name: Test with unittest
      run: python -m unittest -v tests/ppsim_tests.py